ignored-path-predicates:
  - "http://dbpedia.org/ontology/wikiPageWikiLink"
  - "http://dbpedia.org/ontology/wikiPageExternalLink"
  - "http://www.w3.org/2002/07/owl#sameAs"
  - "http://dbpedia.org/property/wikiPageUsesTemplate"
  - "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  - "http://dbpedia.org/ontology/abstract"
  - "http://purl.org/dc/terms/subject"
  - "http://www.w3.org/2000/01/rdf-schema#label"
  - "http://dbpedia.org/ontology/wikiPageRevisionID"
  - "http://xmlns.com/foaf/0.1/depiction"
  - "http://dbpedia.org/ontology/deathPlace"
  - "http://www.w3.org/2000/01/rdf-schema#comment"
  - "http://dbpedia.org/property/wikt"
  - "http://www.w3.org/2000/01/rdf-schema#comment"
  - "http://dbpedia.org/ontology/wikiPageLength"
  - "http://dbpedia.org/property/thesisTitle"
  - "http://dbpedia.org/ontology/thumbnail"
# Valid values:
# "any"
# "date"
# "time"
# "dateTime"
# "dateTimeStamp"
# "duration"
# "duration#dayTimeDuration"
# "duration#yearMonthDuration"
# "gDay"
# "gMonth"
# "gYear"
# "gYearMonth"
# "gMonthDay"
valid-date-formats:
  - "any"
